/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const applyWorkflowInstructions = `Implement tasks from an OpenSpec change using spec-driven development discipline.

**Input**: Optionally specify a change name. If omitted, infer it from conversation context only when unambiguous. If vague or ambiguous, prompt for available changes.

**Core rule**: The OpenSpec artifacts are the implementation contract. Do not implement from memory or from the task checkbox alone. Read the artifacts, map the intended behavior to code and tests, then implement one verified slice at a time.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned exactly one change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` and ask the user which change to apply

   Always announce: "Using change: <name>" and how to override it.

2. **Inspect status and schema**

   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`

   Parse the JSON to identify:
   - \`schemaName\`, especially whether this is \`spec-driven\`
   - Which artifact owns tasks
   - Current progress and blocked state

3. **Get apply instructions**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`contextFiles\`: artifact ID -> concrete file paths
   - Progress and remaining tasks
   - Dynamic state-specific instructions

   **Handle states:**
   - If \`state: "blocked"\`: stop, report missing artifacts, and recommend returning to \`/opsx:propose\`
   - If \`state: "all_done"\`: stop and suggest \`/opsx:review <change-name>\`
   - Otherwise: continue

4. **Read the implementation contract**

   Read every file listed under \`contextFiles\`. For spec-driven changes this normally includes proposal, specs, design, and tasks.

   Also inspect only the repository context needed for the pending task:
   - Existing code paths named by the artifacts
   - Nearby tests and test utilities
   - Project commands and conventions from package/config/docs

   Do not flood context by reading unrelated files.

5. **Build an apply map before editing**

   Before making code changes, summarize:
   - Objective: what user-visible or system behavior must change
   - Contract: requirements, scenarios, design decisions, and non-goals that constrain implementation
   - Pending task order
   - For the next task: files likely to change, acceptance criteria, and verification command(s)
   - Risks or ambiguities that would require artifact updates

   Use this traceability shape:
   \`\`\`markdown
   Requirement/design source -> Task -> Acceptance -> Verification -> Evidence
   \`\`\`

   If a pending task lacks a clear requirement/design source, acceptance criterion, or verification path, tighten the task or ask for clarification before editing.

   If the artifacts conflict with each other, are missing acceptance criteria, or require a design decision not already captured, pause and ask for clarification instead of guessing.

5.5 **Assess task complexity and independence**

   Before implementing, analyze every pending task along two dimensions to decide the execution strategy.

   **Complexity:**
   - **TRIVIAL**: single-line change, rename, obvious fix, no design decisions
   - **SIMPLE**: one file, well-understood scope, straightforward implementation
   - **MODERATE**: 2-5 files, some design decisions, moderate risk
   - **COMPLEX**: cross-cutting, many files, significant design decisions, high risk

   **Independence** (check against OTHER pending tasks):
   - **INDEPENDENT**: does not touch files modified by other pending tasks, no shared state
   - **DEPENDENT**: shares files or state with other pending tasks (must run sequentially)

   **Decision matrix:**

   | Complexity | Independence | Strategy |
   |-----------|-------------|----------|
   | TRIVIAL   | any         | Inline execution, no review needed |
   | SIMPLE    | any         | Inline execution, self-review |
   | MODERATE  | INDEPENDENT | Inline execution (preferred); consider sub-agent if >2 in batch |
   | MODERATE  | DEPENDENT   | Inline execution, sequential order |
   | COMPLEX   | INDEPENDENT | **Sub-agent dispatch** (one fresh agent per task) |
   | COMPLEX   | DEPENDENT   | Inline execution with explicit checkpoints between tasks |

   **When NOT to use sub-agents:** Don't dispatch sub-agents for trivial/simple tasks — the overhead exceeds the benefit. Don't batch sub-agents that share files. Don't use sub-agents when the task requires deep understanding of conversation context (e.g., "refactor this to match the pattern we just discussed").

   Announce the strategy: "Assessing N pending tasks: X inline, Y via sub-agent(s)."

6. **Execute tasks with the chosen strategy**

   **Inline execution** (TRIVIAL, SIMPLE, MODERATE-DEPENDENT, most MODERATE-INDEPENDENT):

   For each pending task:
   - Restate the task and the specific requirements/design sections it satisfies
   - Choose the smallest vertical slice that can be completed and verified
   - Keep edits scoped to the task; do not include opportunistic refactors
   - Prefer existing project patterns, helpers, and abstractions
   - Do not add dependencies, change schemas, or alter public contracts unless the artifacts explicitly call for it or the user confirms

   **Testing discipline:**
   - For new behavior or bug fixes, write or identify a failing/covering test before implementation when the project has a practical test harness
   - For bug fixes, reproduce the bug with a failing test first
   - Implement the minimum code needed to pass the test and satisfy the artifact contract
   - Refactor only after tests pass, and keep behavior unchanged
   - If no automated test is practical, document why and use the strongest available verification: build, typecheck, lint, targeted manual check, or runtime smoke test

   **Completion discipline:**
   - Run the targeted verification for the slice
   - Confirm the result satisfies the mapped acceptance criteria
   - Record the verification evidence: command/check, result, and the key output or reason it could not be run
   - Only then update the task checkbox from \`- [ ]\` to \`- [x]\`
   - Continue to the next pending task unless blocked or interrupted

   Use this evidence entry before marking each task complete:
   \`\`\`markdown
   Task: <task id/title>
   Requirement/design source: <artifact section>
   Changed files:
   - <path>
   Verification:
   - Command/check: <command or manual check>
   - Result: passed | failed | skipped
   - Evidence: <short key output, observation, or skip reason>
   Status: complete | blocked
   \`\`\`

   Failed or skipped verification means the task stays unchecked unless the user explicitly accepts the risk and the skip reason is recorded.

   **Sub-agent dispatch** (COMPLEX-INDEPENDENT tasks, optionally batched MODERATE-INDEPENDENT):

   For each qualifying task, dispatch a fresh sub-agent. Tasks that are both COMPLEX and INDEPENDENT of each other can be dispatched in PARALLEL in a single message with multiple Agent tool calls.

   **Implementer prompt template:**
   \`\`\`
   Implement the following task from the OpenSpec change "<change-name>".

   ## Task
   <task description from tasks.md>

   ## Artifact Context
   <relevant sections from proposal.md, specs/*.md, design.md>

   ## Files
   <expected files to create or modify>

   ## Acceptance Criteria
   <what must be true for this task to be complete>

   ## Verification
   Run this command to verify: <verification command>

   ## Constraints
   - Follow existing project patterns and conventions
   - Do NOT modify files outside the scope of this task
   - Do NOT add new dependencies unless explicitly required by the artifacts
   - <any additional project-specific constraints>
   \`\`\`

   **Two-stage review after each sub-agent completes:**

   *Stage 1 — Spec compliance:* Did the agent build exactly what was requested?
   - Map implementation changes to specific requirements
   - Check every acceptance criterion is satisfied
   - If spec violations found → report as SPEC_ISSUE, pause, and ask user for direction

   *Stage 2 — Code quality:* Is the implementation well-built and safe?
   - Follows project patterns and conventions
   - No unnecessary changes, no opportunistic refactors
   - Tests pass, verification succeeds
   - No new dependencies without artifact justification
   - If quality issues found but spec-compliant → fix inline if trivial (<5 lines), otherwise create a new follow-up task

   **Integration after sub-agent:**
   - After review passes both stages, merge or apply the changes
   - Run verification one final time to confirm
   - Mark the task checkbox complete
   - Announce: "Task <N> complete via sub-agent: <summary>"
   - Continue to the next task

   **Parallel dispatch announcement:**
   When dispatching >1 sub-agent in parallel:
   \`\`\`
   ## Dispatching sub-agents in parallel
   - Task 3: Add auth middleware → sub-agent
   - Task 5: Implement user model → sub-agent
   Both tasks are COMPLEX and INDEPENDENT (no shared files).
   Will review each after completion, then integrate.
   \`\`\`

   **Sub-agent anti-rationalization check:**
   Before dispatching, verify you're not making these excuses:

   | Excuse | Reality |
   |--------|---------|
   | "These tasks share a file, but I'll tell each agent to be careful" | Don't. Shared files = DEPENDENT = inline execution |
   | "This is complex enough for a sub-agent" (for a 10-line change) | Sub-agents have overhead. TRIVIAL/SIMPLE tasks stay inline |
   | "I'll just do everything inline, it's simpler" | COMPLEX × 5 independent tasks takes hours inline vs minutes in parallel |
   | "The sub-agent might make mistakes" | That's what the two-stage review is for. Trust but verify |

7. **Pause conditions**

   Pause and report clearly when:
   - The task is unclear or contradicts another artifact
   - Implementation reveals that the proposal/spec/design/tasks are wrong or incomplete
   - Required verification cannot be run and the risk is material
   - A test failure appears unrelated and needs user direction
   - The user interrupts

   When pausing because artifacts need changes, explain exactly which artifact should be updated and what decision is needed.

8. **Finish with implementation status**

   Show:
   - Tasks completed this session
   - Overall progress
   - Verification commands run and their results
   - Any residual risks or skipped checks

   If all tasks are complete, the next step is \`/opsx:review <change-name>\`.

   Do not run sync or archive automatically. Archive only happens when the user explicitly invokes \`/opsx:archive\`.

**Output During Implementation**

\`\`\`
## Applying: <change-name> (schema: <schema-name>)

Contract map:
- Requirement/design source: <artifact section>
- Task: <task description>
- Acceptance: <what must be true>
- Verification: <command or check>

Working slice: <smallest complete behavior>
[implementation happening]
Verification: <command> -> passed
Evidence: <short key output or observation>
Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete

### Completed This Session
- [x] Task 1
- [x] Task 2

### Verification
- \`<command>\` -> passed

### Evidence Ledger
- Task 1: \`<command/check>\` -> passed (<key output or observation>)

Next step: run \`/opsx:review <change-name>\` to review the implementation against the artifacts.
\`\`\`

**Output On Pause**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Blocker
<specific blocker>

### Needed Decision
<artifact update or user decision needed>
\`\`\`

**Guardrails**
- Read contextFiles before editing
- Treat proposal/specs/design/tasks as the source of truth
- Build an apply map before changing files
- Implement one task and one verified slice at a time
- Prefer test-first for behavior changes and bug fixes
- Mark tasks complete only after verification passes
- Record evidence before marking any task complete
- Keep changes minimal and scoped
- Stop when artifacts and implementation needs diverge
- Suggest review after apply; never auto-archive
- Assess task complexity and independence before choosing execution strategy
- Review every sub-agent's work before integrating (spec compliance + code quality)
- Don't dispatch sub-agents for tasks that share files or are TRIVIAL/SIMPLE`;

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change using spec-driven development, test-first execution, and verified task completion.',
    instructions: applyWorkflowInstructions,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement tasks from an OpenSpec change with spec-driven development',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'spec-driven', 'implementation'],
    content: applyWorkflowInstructions.replace(
      '**Input**: Optionally specify a change name.',
      '**Input**: Optionally specify a change name (e.g., `/opsx:apply add-auth`).'
    ),
  };
}
