/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /opsx:apply

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Confirm exploration depth before creating artifacts**

   OpenSpec's preferred flow is \`/opsx:explore\` first, then \`/opsx:propose\`.

   If this request already has enough exploration context from the conversation or existing artifacts:
   - Briefly summarize the exploration packet: problem, user goal, success criteria, non-goals, constraints, risks/unknowns, options considered, recommended direction, and change name
   - Confirm the proposal boundary is stable enough to write artifacts

   If the user jumped directly to propose without prior exploration, run a compact explore pass inside propose:
   - Restate the request as a concrete problem and desired outcome
   - Inspect project context when relevant before asking questions
   - Brainstorm plausible approaches before converging
   - Use grill-me questioning to expose hidden dependencies, vague acceptance criteria, weak constraints, and untested assumptions
   - Surface users, scope, non-goals, success criteria, affected systems, risks, and verification strategy
   - Ask targeted questions until the decision tree is resolved enough to write stable artifacts
   - Compare 2-3 viable approaches when the implementation path is not obvious
   - Confirm the recommended direction before creating proposal/specs/design/tasks

   Prefer one focused question at a time. Do not create artifacts while major requirements, acceptance criteria, or architecture boundaries are still ambiguous.

   Before creating artifacts, write a compact exploration packet in your working notes and use it as the source for proposal/design/specs/tasks:
   \`\`\`markdown
   Problem -> User Goal -> Success Criteria -> Non-goals -> Constraints -> Risks/Unknowns -> Options Considered -> Recommended Direction -> Change Name
   \`\`\`

3. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`openspec/changes/<name>/\` with \`.openspec.yaml\`.

4. **Get the artifact build order**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

5. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

      While creating artifacts, maintain a requirement-to-execution map:
      \`\`\`markdown
      Requirement <id/name> -> Design decision <section> -> Task <n> -> Verification <command/check>
      \`\`\`

      Every behavior-changing requirement should map to at least one task and one verification path. If a requirement has no implementation task, add one. If a task has no requirement or acceptance criterion, tighten it before continuing.

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`openspec status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

6. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/opsx:apply\` or ask me to implement to start working on the tasks."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`openspec instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Ask enough questions to make the proposal, specs, design, and tasks internally consistent
- Include goals, non-goals, risks, assumptions, success criteria, and verification strategy where the schema allows
- Prefer task entries that include Requirement, Acceptance, Files likely touched, Verification, and Risk when the task artifact format allows it
- Make artifacts internally traceable: proposal intent -> spec requirement/scenario -> design decision -> task -> verification
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- Do not leave requirements without tasks or tasks without acceptance/verification evidence
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /opsx:apply

---

**Input**: The argument after \`/opsx:propose\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Confirm exploration depth before creating artifacts**

   OpenSpec's preferred flow is \`/opsx:explore\` first, then \`/opsx:propose\`.

   If this request already has enough exploration context from the conversation or existing artifacts:
   - Briefly summarize the exploration packet: problem, user goal, success criteria, non-goals, constraints, risks/unknowns, options considered, recommended direction, and change name
   - Confirm the proposal boundary is stable enough to write artifacts

   If the user jumped directly to propose without prior exploration, run a compact explore pass inside propose:
   - Restate the request as a concrete problem and desired outcome
   - Inspect project context when relevant before asking questions
   - Brainstorm plausible approaches before converging
   - Use grill-me questioning to expose hidden dependencies, vague acceptance criteria, weak constraints, and untested assumptions
   - Surface users, scope, non-goals, success criteria, affected systems, risks, and verification strategy
   - Ask targeted questions until the decision tree is resolved enough to write stable artifacts
   - Compare 2-3 viable approaches when the implementation path is not obvious
   - Confirm the recommended direction before creating proposal/specs/design/tasks

   Prefer one focused question at a time. Do not create artifacts while major requirements, acceptance criteria, or architecture boundaries are still ambiguous.

   Before creating artifacts, write a compact exploration packet in your working notes and use it as the source for proposal/design/specs/tasks:
   \`\`\`markdown
   Problem -> User Goal -> Success Criteria -> Non-goals -> Constraints -> Risks/Unknowns -> Options Considered -> Recommended Direction -> Change Name
   \`\`\`

3. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`openspec/changes/<name>/\` with \`.openspec.yaml\`.

4. **Get the artifact build order**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

5. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

      While creating artifacts, maintain a requirement-to-execution map:
      \`\`\`markdown
      Requirement <id/name> -> Design decision <section> -> Task <n> -> Verification <command/check>
      \`\`\`

      Every behavior-changing requirement should map to at least one task and one verification path. If a requirement has no implementation task, add one. If a task has no requirement or acceptance criterion, tighten it before continuing.

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`openspec status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

6. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/opsx:apply\` to start implementing."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`openspec instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Ask enough questions to make the proposal, specs, design, and tasks internally consistent
- Include goals, non-goals, risks, assumptions, success criteria, and verification strategy where the schema allows
- Prefer task entries that include Requirement, Acceptance, Files likely touched, Verification, and Risk when the task artifact format allows it
- Make artifacts internally traceable: proposal intent -> spec requirement/scenario -> design decision -> task -> verification
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- Do not leave requirements without tasks or tasks without acceptance/verification evidence
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`
  };
}
